# This workflow defines a build and test process for your .NET project

name: Build and test

# Triggers the workflow on pushes to the main branch
on:
  push:
    branches: [ main ]

# Jobs section defines the execution environment for the steps
jobs:
  build:
    runs-on: windows-latest  # This workflow will run on a Windows machine

    steps:
    - uses: actions/checkout@v4.1.2

    - name: Setup csc.exe
      uses: yoavain/Setup-CSC@v5
      with: 
        vs-version: '[16.10.1,16.10.4)'
        msbuild-architecture: x64

    - name: Build the solution
      run: msbuild /p:Configuration=Release M-Centres_2.0.sln